In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm, tqdm_notebook, tqdm_pandas

from data.models import Investigator, PoliceUnit
from data_importer.base.storage import AzureStorage
from data_importer.base.cleaner import DataCleaner, strip, titleize, ZFill

In [2]:
storage = AzureStorage(account_name='cpdbv2data', 
                       account_key='your-key-here',
                       share='cleaned-data')

import_db = 'import'

## Read Investigator data

In [3]:
df = pd.read_csv(storage.path_for('complaints/investigators.csv')).loc[:, ['investigators_ID', 'Assignment', 'Current.Rank']]

df = df.rename(columns={
    'investigators_ID': 'id',
    'Assignment': 'unit',
    'Current.Rank': 'current_rank'
})

df = df.drop_duplicates(['id'])

## Clean Investigator data

In [4]:
cleaner = DataCleaner(
    schema={
        'current_rank': [strip, titleize],
        'unit': [strip, ZFill(padding=3)]
    }
)
cleaner.perform(df)

100%|██████████| 2/2 [00:00<00:00,  9.04it/s]

          id unit          current_rank
0          1  013  Lieutenant Of Police
1          2  008    Sergeant Of Police
2          3  608  Lieutenant Of Police
3          4  113  Supervising Inv Ipra
4          5  020    Sergeant Of Police
5          6  001    Sergeant Of Police
6          7  113   Investigator 2 Ipra
7          8  113   Investigator 3 Ipra
8          9  120                 Chief
9         10  113   Investigator 3 Ipra
10        11  016    Sergeant Of Police
11        12  001     Captain Of Police
12        13  113   Investigator 3 Ipra
13        14  124      Training Officer
14        15  113   Investigator 2 Ipra
15        16  113   Investigator 3 Ipra
16        17  025    Sergeant Of Police
17        18  142             Dep Chief
19        19  113   Investigator 2 Ipra
21        20  113   Investigator 2 Ipra
22        21  543    Sergeant Of Police
23        22  007    Sergeant Of Police
24        23  113   Investigator I Ipra
25        24  113   Investigator 3 Ipra
26        25  113   Investigator 3 Ipra
28        26  113   Investigator 3 Ipra
29        27  193        Police Officer
30        28  166    Sergeant Of Police
32        29  702    Sergeant Of Police
33        30  016  Lieutenant Of Police
...      ...  ...                   ...
130034  3169  008   Po/Field Trning Off
130047  3170  011    Sergeant Of Police
130049  3171  006    Sergeant Of Police
130061  3172  129    Sergeant Of Police
130089  3173  005    Sergeant Of Police
130094  3174  019    Sergeant Of Police
130100  3175  022    Sergeant Of Police
130122  3176  005    Sergeant Of Police
130132  3177  003    Sergeant Of Police
130133  3178  007    Sergeant Of Police
130171  3179  009    Sergeant Of Police
130183  3180  019    Sergeant Of Police
130200  3181  007    Sergeant Of Police
130213  3182  022    Sergeant Of Police
130228  3183  011    Sergeant Of Police
130246  3184  002    Sergeant Of Police
130258  3185  011    Sergeant Of Police
130259  3186  714    Sergeant Of Police
130269  3187  025    Sergeant Of Police
130271  3188  006    Sergeant Of Police
130281  3189  012    Sergeant Of Police
130285  3190  714    Sergeant Of Police
130294  3191  011    Sergeant Of Police
130302  3192  009    Sergeant Of Police
130311  3193  006    Sergeant Of Police
130344  3194  019    Sergeant Of Police
130351  3195  012    Sergeant Of Police
130377  3196  010    Sergeant Of Police
130391  3197  011    Sergeant Of Police
130420  3198  003    Sergeant Of Police

[3198 rows x 3 columns]

#### Add `unit_id` field and drop `unit` field
*For each `unit`, get the corresponding `unit_id` from the imported `PoliceUnit` data*

In [5]:
df_units = pd.DataFrame.from_records(PoliceUnit.objects.using(import_db).all().values())

In [6]:
def to_unit_id(unit):
    if not unit:
        return np.NaN
    df_found_units = df_units[df_units['unit_name']==unit]
    if df_found_units.empty:
        return np.NaN
    return df_found_units.iloc[0]['id']

In [7]:
tqdm.pandas(tqdm_notebook(), desc='Get unit id')
df['unit_id'] = df['unit'].progress_apply(to_unit_id)
del df['unit']

A Jupyter Widget

Get unit id: 100%|██████████| 3198/3198 [00:01<00:00, 1622.22it/s]

#### Replace all `NaN` to `None`

In [8]:
df = df.where((pd.notnull(df)), None)

## Import Investigator data

#### Delete existing investigators before importing

In [9]:
Investigator.objects.using(import_db).delete()

(3198, {u'data.Investigator': 3198})

#### Import and Print out Investigator data

In [10]:
tqdm.pandas(tqdm_notebook(), desc='Import Investigator')
df.progress_apply(lambda x: Investigator.objects.using(import_db).create(**x), axis=1)

pd.DataFrame.from_records(Investigator.objects.using(import_db).all().values())

A Jupyter Widget

Import Investigator: 105it [00:00, 1043.73it/s]

Import Investigator: 3198it [00:02, 1089.63it/s]

              current_rank    id name raw_name  unit_id
0     Lieutenant Of Police     1                   14.0
1       Sergeant Of Police     2                    9.0
2     Lieutenant Of Police     3                  201.0
3       Sergeant Of Police  3031                   13.0
4       Sergeant Of Police  3032                   20.0
5       Sergeant Of Police  3033                   62.0
6       Sergeant Of Police  3034                   26.0
7       Sergeant Of Police  3035                    7.0
8       Sergeant Of Police  3036                  210.0
9       Sergeant Of Police  3037                   19.0
10      Sergeant Of Police  3038                  210.0
11      Sergeant Of Police  3039                   19.0
12      Sergeant Of Police  3040                  220.0
13      Sergeant Of Police  3041                  135.0
14      Sergeant Of Police  3042                    6.0
15      Sergeant Of Police  3043                    6.0
16      Sergeant Of Police  3044                  151.0
17      Sergeant Of Police  3045                    2.0
18          Police Officer  3046                   74.0
19      Sergeant Of Police  3047                    9.0
20      Sergeant Of Police  3048                   20.0
21      Sergeant Of Police  3049                   35.0
22      Sergeant Of Police  3050                   69.0
23      Sergeant Of Police  3051                    6.0
24      Sergeant Of Police  3052                   25.0
25      Sergeant Of Police  3053                   11.0
26      Sergeant Of Police  3054                  220.0
27      Sergeant Of Police  3055                    7.0
28      Sergeant Of Police  3056                  203.0
29      Sergeant Of Police  3057                   74.0
...                    ...   ...  ...      ...      ...
3168    Sergeant Of Police  3001                   21.0
3169    Sergeant Of Police  3002                    6.0
3170    Sergeant Of Police  3003                   21.0
3171    Sergeant Of Police  3004                  168.0
3172    Sergeant Of Police  3005                    6.0
3173    Sergeant Of Police  3006                  142.0
3174    Sergeant Of Police  3007                    9.0
3175    Sergeant Of Police  3008                   15.0
3176    Sergeant Of Police  3009                   25.0
3177    Sergeant Of Police  3010                   16.0
3178    Sergeant Of Police  3011                   21.0
3179    Sergeant Of Police  3012                   19.0
3180    Sergeant Of Police  3013                   38.0
3181    Sergeant Of Police  3014                   78.0
3182    Sergeant Of Police  3015                   74.0
3183    Sergeant Of Police  3016                  100.0
3184    Sergeant Of Police  3017                   13.0
3185    Sergeant Of Police  3018                   20.0
3186    Sergeant Of Police  3019                   12.0
3187    Sergeant Of Police  3020                   20.0
3188        Police Officer  3021                   76.0
3189    Sergeant Of Police  3022                   19.0
3190    Sergeant Of Police  3023                    2.0
3191    Sergeant Of Police  3024                    8.0
3192    Sergeant Of Police  3025                  146.0
3193    Sergeant Of Police  3026                   25.0
3194    Sergeant Of Police  3027                    8.0
3195    Sergeant Of Police  3028                   25.0
3196    Sergeant Of Police  3029                   26.0
3197    Sergeant Of Police  3030                   20.0

[3198 rows x 5 columns]