In [1]:
import pandas as pd
import numpy as np
from tqdm import tqdm, tqdm_notebook, tqdm_pandas

from data.models import Complainant, Allegation
from data_importer.base.cleaner import DataCleaner, strip, titleize
from data_importer.base.storage import AzureStorage

In [2]:
storage = AzureStorage(account_name='cpdbv2data', 
                       account_key='your-key-here',
                       share='cleaned-data')
import_db = 'import'

In [3]:
gender_dict = {
    'MALE': 'M',
    'FEMALE': 'F',
    'UNKNOWN': 'X'
}

## Read Complainants data

In [4]:
df = pd.read_csv(
    storage.path_for('complaints/complainants.csv')
)

df = df.rename(columns={
    'CRID': 'crid',
    'Gender': 'gender',
    'Age': 'age',
    'Race': 'race'
})

## Clean Complaints data

In [5]:
cleaner = DataCleaner(
    schema={
        'race': [strip, titleize],
        'gender': [lambda x: gender_dict.get(x, '')],
        'age': [lambda x: round(x, 0) if x != None else None],
        'crid': [strip]
    }
)
cleaner.perform(df)

100%|██████████| 4/4 [00:02<00:00,  1.31it/s]

           crid gender    age      race
0       1000000      F   49.0     White
1       1000001      M   32.0     Black
2       1000002      M   43.0  Hispanic
3       1000004      M   60.0  Hispanic
4       1000004      M   53.0     White
5       1000005      F   35.0     Black
6       1000006      M   53.0     Black
7       1000007      F   56.0     White
8       1000009      M   39.0  Hispanic
9       1000010      M   43.0     Black
10      1000014      F   55.0     Black
11      1000015      F    NaN     Black
12      1000016      M   67.0     Black
13      1000017      F   34.0  Hispanic
14      1000018      M    NaN   Unknown
15      1000020      M   33.0     Black
16      1000021      F   55.0     Black
17      1000022      F   68.0     Black
18      1000023      M   52.0     Black
19      1000024      F   32.0  Hispanic
20      1000025      F   52.0  Hispanic
21      1000026      F    NaN     Black
22      1000026      F   28.0     Black
23      1000027      F    NaN  Hispanic
24      1000028      M   35.0  Hispanic
25      1000030      M   37.0     Black
26      1000031      F   44.0     Black
27      1000033      M   60.0     Black
28      1000034      F   57.0     Black
29      1000035      F   58.0     White
...         ...    ...    ...       ...
48184   1081975      M   35.0     Black
48185   1081979      M -901.0   Unknown
48186   1081980      M   46.0     Black
48187   1081981      M    NaN     White
48188   1081981      M   56.0     Black
48189   1081994      F   48.0     Black
48190   1082005      M    NaN   Unknown
48191   1082047      M    NaN   Unknown
48192   1082049      M    NaN     White
48193   1082050      F    NaN   Unknown
48194   1082068      M    NaN   Unknown
48195   1082094      M    NaN   Unknown
48196   1082097      M    NaN   Unknown
48197   1082100      M   41.0     Black
48198   1082102      M    NaN     White
48199   1082182      M    NaN   Unknown
48200   1082189      M   45.0     Black
48201   1082322      M   39.0     Black
48202   1082361      M    NaN   Unknown
48203   1082402      M   41.0  Hispanic
48204   1082467      F    NaN     White
48205   1082499      F    NaN   Unknown
48206   1082516      M    NaN   Unknown
48207   1082599      F    NaN   Unknown
48208   1082600      M    NaN   Unknown
48209   1082657      M    NaN   Unknown
48210   1082661      M    NaN   Unknown
48211  10773250      F   53.0     Black
48212  10819810      M   46.0     Black
48213  10851356      M   54.0     Black

[48214 rows x 4 columns]

#### Replace invalid ages (<= 0 or > 100) with `None`

In [6]:
df['age'] = df['age'].where((df['age'] > 0) & (df['age'] <= 100), None)

#### Get the allegation's ids which complainants are associated with

In [7]:
crid_to_id_map = {}
for id, crid in Allegation.objects.using(import_db).all().values_list('id', 'crid'):
    crid_to_id_map[crid] = id

In [8]:
tqdm.pandas(tqdm_notebook(), desc='Get allegation id')
df['allegation_id'] = df['crid'].progress_apply(lambda x: crid_to_id_map.get(x, None))
del df['crid']

A Jupyter Widget

Get allegation id: 100%|██████████| 48214/48214 [00:00<00:00, 750562.94it/s]

## Import Complainants data

#### Delete existing complainants before importing

In [9]:
Complainant.objects.using(import_db).delete()

(0, {u'data.Complainant': 0})

#### Import complainants data and print out the imported data

In [10]:
tqdm.pandas(tqdm_notebook(), desc='Importing complainant data')
df.progress_apply(lambda x: Complainant.objects.using(import_db).create(**x), axis=1)

pd.DataFrame.from_records(Complainant.objects.using(import_db).all().values())

A Jupyter Widget

Importing complainant data: 100it [00:00, 997.19it/s]

Importing complainant data: 48214it [00:47, 1008.80it/s]

        age  allegation_id gender     id      race
0      49.0          56650      F      1     White
1      32.0          56651      M      2     Black
2      43.0          56652      M      3  Hispanic
3      60.0          56653      M      4  Hispanic
4      53.0          56653      M      5     White
5      35.0          56654      F      6     Black
6      53.0          56655      M      7     Black
7      56.0          56656      F      8     White
8      39.0          56657      M      9  Hispanic
9      43.0          56658      M     10     Black
10     55.0          56659      F     11     Black
11      NaN          56660      F     12     Black
12     67.0          56661      M     13     Black
13     34.0          56662      F     14  Hispanic
14      NaN          56663      M     15   Unknown
15     33.0          56664      M     16     Black
16     55.0          56665      F     17     Black
17     68.0          56666      F     18     Black
18     52.0          56667      M     19     Black
19     32.0          56668      F     20  Hispanic
20     52.0          56669      F     21  Hispanic
21      NaN          56670      F     22     Black
22     28.0          56670      F     23     Black
23      NaN          56671      F     24  Hispanic
24     35.0          56672      M     25  Hispanic
25     37.0          56673      M     26     Black
26     44.0          56674      F     27     Black
27     60.0          56675      M     28     Black
28     57.0          56676      F     29     Black
29     58.0          56677      F     30     White
...     ...            ...    ...    ...       ...
48184  35.0         109290      M  48185     Black
48185   NaN         109291      M  48186   Unknown
48186  46.0         109292      M  48187     Black
48187   NaN         109293      M  48188     White
48188  56.0         109293      M  48189     Black
48189  48.0         109294      F  48190     Black
48190   NaN         109296      M  48191   Unknown
48191   NaN         109297      M  48192   Unknown
48192   NaN         109298      M  48193     White
48193   NaN         109299      F  48194   Unknown
48194   NaN         109300      M  48195   Unknown
48195   NaN         109301      M  48196   Unknown
48196   NaN         109302      M  48197   Unknown
48197  41.0         109303      M  48198     Black
48198   NaN         109304      M  48199     White
48199   NaN         109307      M  48200   Unknown
48200  45.0         109308      M  48201     Black
48201  39.0         109312      M  48202     Black
48202   NaN         109317      M  48203   Unknown
48203  41.0         109318      M  48204  Hispanic
48204   NaN         109322      F  48205     White
48205   NaN         109324      F  48206   Unknown
48206   NaN         109326      M  48207   Unknown
48207   NaN         109328      F  48208   Unknown
48208   NaN         109329      M  48209   Unknown
48209   NaN         109332      M  48210   Unknown
48210   NaN         109333      M  48211   Unknown
48211  53.0         109337      F  48212     Black
48212  46.0         109338      M  48213     Black
48213  54.0         109339      M  48214     Black

[48214 rows x 5 columns]