In [10]:
import pandas as pd
from tqdm import tqdm

from data.models import Officer
from data_importer.base.storage import AzureStorage
from data_importer.base.cleaner import DataCleaner, strip, titleize

In [11]:
storage = AzureStorage(account_name='cpdbv2data', 
                       account_key='azure_storage_account_key',
                       share='cleaned-data')

## Read Officer Profiles data

In [12]:
df = pd.read_csv(storage.path_for('profiles/officer-profiles.csv'))
df = df.loc[:, 
    ['UID', 'Gender', 'Appointed.Date', 'Race', 'Birth.Year', 
     'Last.Name', 'First.Name', 'Suffix.Name', 'Middle.Initial']
]
df = df.rename(columns={
    'UID': 'id',
    'Gender': 'gender', 
    'Appointed.Date': 'appointed_date', 
    'Race': 'race', 
    'Birth.Year': 'birth_year',
    'Last.Name': 'last_name',
    'First.Name': 'first_name',
    'Suffix.Name': 'suffix_name',
    'Middle.Initial': 'middle_initial'
})

## Clean up the data

In [13]:
cleaner = DataCleaner(
    schema={
        'first_name': [strip, titleize],
        'last_name': [strip, titleize],
        'gender': [strip, titleize],
        'race': [strip],
    }
)
cleaner.perform(df)

100%|██████████| 4/4 [00:02<00:00,  1.39it/s]

,id,gender,appointed_date,race,birth_year,last_name,first_name,suffix_name,middle_initial
0,1,Male,2005-09-26,WHITE,1971.0,Aaron,Jeffery,NaN,M
1,2,Female,2005-09-26,HISPANIC,1980.0,Aaron,Karina,NaN,NaN
2,3,Male,1970-06-15,WHITE,1942.0,Abate,Daniel,NaN,P
3,4,Male,1994-12-05,WHITE,1968.0,Abbate,Anthony,NaN,G
4,5,Male,1969-01-06,WHITE,1942.0,Abbate,Carmel,NaN,G
5,6,Male,1954-10-16,WHITE,1930.0,Abbate,Carmen,NaN,S
6,7,Male,1995-12-04,WHITE,1972.0,Abbate,Terry,NaN,M
7,8,Male,1990-03-26,BLACK,1945.0,Abbey,Leon,NaN,B
8,9,Male,1949-03-16,BLACK,1923.0,Abbey,Leon,NaN,NaN
9,10,Male,1976-04-26,BLACK,1952.0,Abbey,Michael,NaN,J
10,11,Male,1970-12-14,WHITE,1949.0,Abbott,Andrew,NaN,A
11,12,Male,1982-11-29,WHITE,1953.0,Abbott,Dale,NaN,E
12,13,Female,1987-12-07,WHITE,1958.0,Abbott,Elizabeth,NaN,L
13,14,Female,1986-07-14,WHITE,1965.0,Abbott,Laura,NaN,F
14,15,Male,2012-11-30,WHITE,1983.0,Abdallah,Zaid,NaN,F
15,16,Male,2006-12-18,WHITE,1978.0,Abdelhadi,Abdalmahd,NaN,NaN
16,17,Male,2008-04-28,API,1984.0,Abdelmajeid,Aziz,NaN,NaN
17,18,Male,1989-12-26,BLACK,1958.0,Abdullah,Moulay,NaN,R
18,19,Male,1999-10-25,API,1976.0,Abejero,Jason,NaN,V
19,20,Male,1999-12-13,API,1949.0,Abejero,Restituto,NaN,E
20,21,Male,1970-06-15,WHITE,1949.0,Abels,Kenneth,NaN,L
21,22,Female,1985-09-09,WHITE,1957.0,Abelson,Deborah,NaN,M
22,23,Male,1964-06-08,BLACK,1937.0,Abington,Eugene,NaN,B
23,24,Male,2015-06-29,WHITE,1990.0,Abney,Patrick,NaN,R
24,25,Male,1947-12-22,WHITE,1925.0,Abraham,John,NaN,NaN
25,26,Male,1950-04-03,WHITE,1922.0,Abraham,Jos,NaN,H
26,27,Female,2014-04-28,API,1986.0,Abraham,Nancy,NaN,A
27,28,Male,2016-06-27,BLACK,1988.0,Abram,Anthony,NaN,A
28,29,Male,1976-04-26,BLACK,1939.0,Abram,Paul,NaN,W
29,30,Male,1986-06-16,BLACK,1963.0,Abrams,Henry,NaN,L
...,...,...,...,...,...,...,...,...,...
32110,32111,Male,1998-10-01,NaN,1942.0,Rake,Kevin,NaN,NaN
32111,32112,Male,2017-03-16,NaN,1979.0,Ramos,Esteban,NaN,NaN
32112,32113,Male,2016-12-12,NaN,1981.0,Regalado,Anthony,NaN,NaN
32113,32114,Male,2016-10-31,NaN,1990.0,Roberson,Divale,NaN,NaN
32114,32115,Male,2004-01-26,NaN,1966.0,Roberts,Sean,NaN,NaN
32115,32116,Female,2010-04-16,NaN,1985.0,Rodriguez,Jacqueline,NaN,NaN
32116,32117,Male,2012-12-14,NaN,1986.0,Rusin,Christopher,NaN,NaN
32117,32118,Male,2016-10-31,NaN,1990.0,Saleh,Adnan,NaN,NaN
32118,32119,Male,2016-10-31,NaN,1983.0,Sas,Michael,NaN,NaN
32119,32120,Male,1990-07-10,NaN,1966.0,Sebok,David,NaN,NaN
32120,32121,Male,2007-11-01,NaN,1988.0,Shiu,Christian,NaN,NaN
32121,32122,Male,2016-12-12,NaN,1992.0,Slater,Tyrell,NaN,NaN
32122,32123,Male,2012-07-02,NaN,1980.0,Smith,Seneca,NaN,NaN
32123,32124,Male,2017-03-16,NaN,1977.0,Sourn,Nivath,NaN,NaN
32124,32125,Male,2016-10-31,NaN,1992.0,Spizzirri,Michaelr,NaN,NaN
32125,32126,Male,2006-04-28,NaN,1987.0,Stewart,James,NaN,NaN
32126,32127,Male,2007-11-01,NaN,1986.0,Taylor,Kevin,NaN,NaN
32127,32128,Female,2007-06-18,NaN,1990.0,Vega,Lynnette,NaN,NaN
32128,32129,Male,2016-12-12,NaN,1980.0,Venegas,Joel,NaN,NaN
32129,32130,Male,2004-09-27,NaN,1972.0,Vonreichbauer,Jason,NaN,NaN
32130,32131,Male,2016-10-31,NaN,1990.0,Wantroba,Kyle,NaN,NaN
32131,32132,Female,2005-09-16,NaN,1987.0,Watson,Mercedes,NaN,NaN
32132,32133,Female,2010-04-16,NaN,1981.0,Weber,Maureen,NaN,NaN
32133,32134,Male,2007-11-01,NaN,1987.0,White,Dwight,NaN,NaN
32134,32135,Female,2006-04-28,NaN,1986.0,White,Quinretta,NaN,NaN
32135,32136,Male,2016-12-12,NaN,1991.0,Wilczek,Grzegorz,NaN,NaN
32136,32137,Male,2008-04-07,NaN,1977.0,Wilson,Michael,NaN,NaN
32137,32138,Male,2002-01-07,NaN,1978.0,Witnik,Steven,NaN,NaN
32138,32139,Male,2013-11-16,NaN,1995.0,Wright,Nicholas,NaN,NaN
32139,32140,Female,2016-08-29,NaN,1988.0,Zuk,Edyta,NaN,NaN

#### Fill all missing values with None

In [14]:
df = df.where((pd.notnull(df)), None)

#### Change gender format to M/F/X

In [15]:
df['gender'] = df['gender'].apply(lambda x: 'M' if x == 'Male' else 'F' if x == 'Female' else 'X' if x == 'Unknown' else '')
df

,id,gender,appointed_date,race,birth_year,last_name,first_name,suffix_name,middle_initial
0,1,M,2005-09-26,WHITE,1971,Aaron,Jeffery,None,M
1,2,F,2005-09-26,HISPANIC,1980,Aaron,Karina,None,None
2,3,M,1970-06-15,WHITE,1942,Abate,Daniel,None,P
3,4,M,1994-12-05,WHITE,1968,Abbate,Anthony,None,G
4,5,M,1969-01-06,WHITE,1942,Abbate,Carmel,None,G
5,6,M,1954-10-16,WHITE,1930,Abbate,Carmen,None,S
6,7,M,1995-12-04,WHITE,1972,Abbate,Terry,None,M
7,8,M,1990-03-26,BLACK,1945,Abbey,Leon,None,B
8,9,M,1949-03-16,BLACK,1923,Abbey,Leon,None,None
9,10,M,1976-04-26,BLACK,1952,Abbey,Michael,None,J
10,11,M,1970-12-14,WHITE,1949,Abbott,Andrew,None,A
11,12,M,1982-11-29,WHITE,1953,Abbott,Dale,None,E
12,13,F,1987-12-07,WHITE,1958,Abbott,Elizabeth,None,L
13,14,F,1986-07-14,WHITE,1965,Abbott,Laura,None,F
14,15,M,2012-11-30,WHITE,1983,Abdallah,Zaid,None,F
15,16,M,2006-12-18,WHITE,1978,Abdelhadi,Abdalmahd,None,None
16,17,M,2008-04-28,API,1984,Abdelmajeid,Aziz,None,None
17,18,M,1989-12-26,BLACK,1958,Abdullah,Moulay,None,R
18,19,M,1999-10-25,API,1976,Abejero,Jason,None,V
19,20,M,1999-12-13,API,1949,Abejero,Restituto,None,E
20,21,M,1970-06-15,WHITE,1949,Abels,Kenneth,None,L
21,22,F,1985-09-09,WHITE,1957,Abelson,Deborah,None,M
22,23,M,1964-06-08,BLACK,1937,Abington,Eugene,None,B
23,24,M,2015-06-29,WHITE,1990,Abney,Patrick,None,R
24,25,M,1947-12-22,WHITE,1925,Abraham,John,None,None
25,26,M,1950-04-03,WHITE,1922,Abraham,Jos,None,H
26,27,F,2014-04-28,API,1986,Abraham,Nancy,None,A
27,28,M,2016-06-27,BLACK,1988,Abram,Anthony,None,A
28,29,M,1976-04-26,BLACK,1939,Abram,Paul,None,W
29,30,M,1986-06-16,BLACK,1963,Abrams,Henry,None,L
...,...,...,...,...,...,...,...,...,...
32110,32111,M,1998-10-01,None,1942,Rake,Kevin,None,None
32111,32112,M,2017-03-16,None,1979,Ramos,Esteban,None,None
32112,32113,M,2016-12-12,None,1981,Regalado,Anthony,None,None
32113,32114,M,2016-10-31,None,1990,Roberson,Divale,None,None
32114,32115,M,2004-01-26,None,1966,Roberts,Sean,None,None
32115,32116,F,2010-04-16,None,1985,Rodriguez,Jacqueline,None,None
32116,32117,M,2012-12-14,None,1986,Rusin,Christopher,None,None
32117,32118,M,2016-10-31,None,1990,Saleh,Adnan,None,None
32118,32119,M,2016-10-31,None,1983,Sas,Michael,None,None
32119,32120,M,1990-07-10,None,1966,Sebok,David,None,None
32120,32121,M,2007-11-01,None,1988,Shiu,Christian,None,None
32121,32122,M,2016-12-12,None,1992,Slater,Tyrell,None,None
32122,32123,M,2012-07-02,None,1980,Smith,Seneca,None,None
32123,32124,M,2017-03-16,None,1977,Sourn,Nivath,None,None
32124,32125,M,2016-10-31,None,1992,Spizzirri,Michaelr,None,None
32125,32126,M,2006-04-28,None,1987,Stewart,James,None,None
32126,32127,M,2007-11-01,None,1986,Taylor,Kevin,None,None
32127,32128,F,2007-06-18,None,1990,Vega,Lynnette,None,None
32128,32129,M,2016-12-12,None,1980,Venegas,Joel,None,None
32129,32130,M,2004-09-27,None,1972,Vonreichbauer,Jason,None,None
32130,32131,M,2016-10-31,None,1990,Wantroba,Kyle,None,None
32131,32132,F,2005-09-16,None,1987,Watson,Mercedes,None,None
32132,32133,F,2010-04-16,None,1981,Weber,Maureen,None,None
32133,32134,M,2007-11-01,None,1987,White,Dwight,None,None
32134,32135,F,2006-04-28,None,1986,White,Quinretta,None,None
32135,32136,M,2016-12-12,None,1991,Wilczek,Grzegorz,None,None
32136,32137,M,2008-04-07,None,1977,Wilson,Michael,None,None
32137,32138,M,2002-01-07,None,1978,Witnik,Steven,None,None
32138,32139,M,2013-11-16,None,1995,Wright,Nicholas,None,None
32139,32140,F,2016-08-29,None,1988,Zuk,Edyta,None,None

#### Replace None with `''`

In [16]:
df['race'] = df['race'].apply(lambda x: x if x is not None else '')
df

,id,gender,appointed_date,race,birth_year,last_name,first_name,suffix_name,middle_initial
0,1,M,2005-09-26,WHITE,1971,Aaron,Jeffery,None,M
1,2,F,2005-09-26,HISPANIC,1980,Aaron,Karina,None,None
2,3,M,1970-06-15,WHITE,1942,Abate,Daniel,None,P
3,4,M,1994-12-05,WHITE,1968,Abbate,Anthony,None,G
4,5,M,1969-01-06,WHITE,1942,Abbate,Carmel,None,G
5,6,M,1954-10-16,WHITE,1930,Abbate,Carmen,None,S
6,7,M,1995-12-04,WHITE,1972,Abbate,Terry,None,M
7,8,M,1990-03-26,BLACK,1945,Abbey,Leon,None,B
8,9,M,1949-03-16,BLACK,1923,Abbey,Leon,None,None
9,10,M,1976-04-26,BLACK,1952,Abbey,Michael,None,J
10,11,M,1970-12-14,WHITE,1949,Abbott,Andrew,None,A
11,12,M,1982-11-29,WHITE,1953,Abbott,Dale,None,E
12,13,F,1987-12-07,WHITE,1958,Abbott,Elizabeth,None,L
13,14,F,1986-07-14,WHITE,1965,Abbott,Laura,None,F
14,15,M,2012-11-30,WHITE,1983,Abdallah,Zaid,None,F
15,16,M,2006-12-18,WHITE,1978,Abdelhadi,Abdalmahd,None,None
16,17,M,2008-04-28,API,1984,Abdelmajeid,Aziz,None,None
17,18,M,1989-12-26,BLACK,1958,Abdullah,Moulay,None,R
18,19,M,1999-10-25,API,1976,Abejero,Jason,None,V
19,20,M,1999-12-13,API,1949,Abejero,Restituto,None,E
20,21,M,1970-06-15,WHITE,1949,Abels,Kenneth,None,L
21,22,F,1985-09-09,WHITE,1957,Abelson,Deborah,None,M
22,23,M,1964-06-08,BLACK,1937,Abington,Eugene,None,B
23,24,M,2015-06-29,WHITE,1990,Abney,Patrick,None,R
24,25,M,1947-12-22,WHITE,1925,Abraham,John,None,None
25,26,M,1950-04-03,WHITE,1922,Abraham,Jos,None,H
26,27,F,2014-04-28,API,1986,Abraham,Nancy,None,A
27,28,M,2016-06-27,BLACK,1988,Abram,Anthony,None,A
28,29,M,1976-04-26,BLACK,1939,Abram,Paul,None,W
29,30,M,1986-06-16,BLACK,1963,Abrams,Henry,None,L
...,...,...,...,...,...,...,...,...,...
32110,32111,M,1998-10-01,,1942,Rake,Kevin,None,None
32111,32112,M,2017-03-16,,1979,Ramos,Esteban,None,None
32112,32113,M,2016-12-12,,1981,Regalado,Anthony,None,None
32113,32114,M,2016-10-31,,1990,Roberson,Divale,None,None
32114,32115,M,2004-01-26,,1966,Roberts,Sean,None,None
32115,32116,F,2010-04-16,,1985,Rodriguez,Jacqueline,None,None
32116,32117,M,2012-12-14,,1986,Rusin,Christopher,None,None
32117,32118,M,2016-10-31,,1990,Saleh,Adnan,None,None
32118,32119,M,2016-10-31,,1983,Sas,Michael,None,None
32119,32120,M,1990-07-10,,1966,Sebok,David,None,None
32120,32121,M,2007-11-01,,1988,Shiu,Christian,None,None
32121,32122,M,2016-12-12,,1992,Slater,Tyrell,None,None
32122,32123,M,2012-07-02,,1980,Smith,Seneca,None,None
32123,32124,M,2017-03-16,,1977,Sourn,Nivath,None,None
32124,32125,M,2016-10-31,,1992,Spizzirri,Michaelr,None,None
32125,32126,M,2006-04-28,,1987,Stewart,James,None,None
32126,32127,M,2007-11-01,,1986,Taylor,Kevin,None,None
32127,32128,F,2007-06-18,,1990,Vega,Lynnette,None,None
32128,32129,M,2016-12-12,,1980,Venegas,Joel,None,None
32129,32130,M,2004-09-27,,1972,Vonreichbauer,Jason,None,None
32130,32131,M,2016-10-31,,1990,Wantroba,Kyle,None,None
32131,32132,F,2005-09-16,,1987,Watson,Mercedes,None,None
32132,32133,F,2010-04-16,,1981,Weber,Maureen,None,None
32133,32134,M,2007-11-01,,1987,White,Dwight,None,None
32134,32135,F,2006-04-28,,1986,White,Quinretta,None,None
32135,32136,M,2016-12-12,,1991,Wilczek,Grzegorz,None,None
32136,32137,M,2008-04-07,,1977,Wilson,Michael,None,None
32137,32138,M,2002-01-07,,1978,Witnik,Steven,None,None
32138,32139,M,2013-11-16,,1995,Wright,Nicholas,None,None
32139,32140,F,2016-08-29,,1988,Zuk,Edyta,None,None

## Import officer profiles

#### Delete all existing officers before importing

In [17]:
import_db = 'import'
Officer.objects.using(import_db).delete()

(0, {})

In [18]:
officer_dicts = df.to_dict(orient='records')

for officer_dict in tqdm(officer_dicts):
    officer = Officer(**officer_dict)
    officer.save(using=import_db)

Officer.objects.using(import_db).count()

100%|██████████| 32140/32140 [00:46<00:00, 693.50it/s]

32140

## Print out the imported data

In [19]:
df_imported_officers = pd.DataFrame.from_records(Officer.objects.using(import_db).all().values()).sort_values('id')
df_imported_officers

,active,appointed_date,birth_year,first_name,gender,id,last_name,middle_initial,race,rank,suffix_name,tags
0,Unknown,2005-09-26,1971.0,Jeffery,M,1,Aaron,M,WHITE,,None,[]
1,Unknown,2005-09-26,1980.0,Karina,F,2,Aaron,None,HISPANIC,,None,[]
2,Unknown,1970-06-15,1942.0,Daniel,M,3,Abate,P,WHITE,,None,[]
3,Unknown,1994-12-05,1968.0,Anthony,M,4,Abbate,G,WHITE,,None,[]
4,Unknown,1969-01-06,1942.0,Carmel,M,5,Abbate,G,WHITE,,None,[]
5,Unknown,1954-10-16,1930.0,Carmen,M,6,Abbate,S,WHITE,,None,[]
6,Unknown,1995-12-04,1972.0,Terry,M,7,Abbate,M,WHITE,,None,[]
7,Unknown,1990-03-26,1945.0,Leon,M,8,Abbey,B,BLACK,,None,[]
8,Unknown,1949-03-16,1923.0,Leon,M,9,Abbey,None,BLACK,,None,[]
9,Unknown,1976-04-26,1952.0,Michael,M,10,Abbey,J,BLACK,,None,[]
10,Unknown,1970-12-14,1949.0,Andrew,M,11,Abbott,A,WHITE,,None,[]
11,Unknown,1982-11-29,1953.0,Dale,M,12,Abbott,E,WHITE,,None,[]
12,Unknown,1987-12-07,1958.0,Elizabeth,F,13,Abbott,L,WHITE,,None,[]
13,Unknown,1986-07-14,1965.0,Laura,F,14,Abbott,F,WHITE,,None,[]
14,Unknown,2012-11-30,1983.0,Zaid,M,15,Abdallah,F,WHITE,,None,[]
15,Unknown,2006-12-18,1978.0,Abdalmahd,M,16,Abdelhadi,None,WHITE,,None,[]
16,Unknown,2008-04-28,1984.0,Aziz,M,17,Abdelmajeid,None,API,,None,[]
17,Unknown,1989-12-26,1958.0,Moulay,M,18,Abdullah,R,BLACK,,None,[]
18,Unknown,1999-10-25,1976.0,Jason,M,19,Abejero,V,API,,None,[]
19,Unknown,1999-12-13,1949.0,Restituto,M,20,Abejero,E,API,,None,[]
20,Unknown,1970-06-15,1949.0,Kenneth,M,21,Abels,L,WHITE,,None,[]
21,Unknown,1985-09-09,1957.0,Deborah,F,22,Abelson,M,WHITE,,None,[]
22,Unknown,1964-06-08,1937.0,Eugene,M,23,Abington,B,BLACK,,None,[]
23,Unknown,2015-06-29,1990.0,Patrick,M,24,Abney,R,WHITE,,None,[]
24,Unknown,1947-12-22,1925.0,John,M,25,Abraham,None,WHITE,,None,[]
25,Unknown,1950-04-03,1922.0,Jos,M,26,Abraham,H,WHITE,,None,[]
26,Unknown,2014-04-28,1986.0,Nancy,F,27,Abraham,A,API,,None,[]
27,Unknown,2016-06-27,1988.0,Anthony,M,28,Abram,A,BLACK,,None,[]
28,Unknown,1976-04-26,1939.0,Paul,M,29,Abram,W,BLACK,,None,[]
29,Unknown,1986-06-16,1963.0,Henry,M,30,Abrams,L,BLACK,,None,[]
...,...,...,...,...,...,...,...,...,...,...,...,...
32110,Unknown,1998-10-01,1942.0,Kevin,M,32111,Rake,None,,,None,[]
32111,Unknown,2017-03-16,1979.0,Esteban,M,32112,Ramos,None,,,None,[]
32112,Unknown,2016-12-12,1981.0,Anthony,M,32113,Regalado,None,,,None,[]
32113,Unknown,2016-10-31,1990.0,Divale,M,32114,Roberson,None,,,None,[]
32114,Unknown,2004-01-26,1966.0,Sean,M,32115,Roberts,None,,,None,[]
32115,Unknown,2010-04-16,1985.0,Jacqueline,F,32116,Rodriguez,None,,,None,[]
32116,Unknown,2012-12-14,1986.0,Christopher,M,32117,Rusin,None,,,None,[]
32117,Unknown,2016-10-31,1990.0,Adnan,M,32118,Saleh,None,,,None,[]
32118,Unknown,2016-10-31,1983.0,Michael,M,32119,Sas,None,,,None,[]
32119,Unknown,1990-07-10,1966.0,David,M,32120,Sebok,None,,,None,[]
32120,Unknown,2007-11-01,1988.0,Christian,M,32121,Shiu,None,,,None,[]
32121,Unknown,2016-12-12,1992.0,Tyrell,M,32122,Slater,None,,,None,[]
32122,Unknown,2012-07-02,1980.0,Seneca,M,32123,Smith,None,,,None,[]
32123,Unknown,2017-03-16,1977.0,Nivath,M,32124,Sourn,None,,,None,[]
32124,Unknown,2016-10-31,1992.0,Michaelr,M,32125,Spizzirri,None,,,None,[]
32125,Unknown,2006-04-28,1987.0,James,M,32126,Stewart,None,,,None,[]
32126,Unknown,2007-11-01,1986.0,Kevin,M,32127,Taylor,None,,,None,[]
32127,Unknown,2007-06-18,1990.0,Lynnette,F,32128,Vega,None,,,None,[]
32128,Unknown,2016-12-12,1980.0,Joel,M,32129,Venegas,None,,,None,[]
32129,Unknown,2004-09-27,1972.0,Jason,M,32130,Vonreichbauer,None,,,None,[]
32130,Unknown,2016-10-31,1990.0,Kyle,M,32131,Wantroba,None,,,None,[]
32131,Unknown,2005-09-16,1987.0,Mercedes,F,32132,Watson,None,,,None,[]
32132,Unknown,2010-04-16,1981.0,Maureen,F,32133,Weber,None,,,None,[]
32133,Unknown,2007-11-01,1987.0,Dwight,M,32134,White,None,,,None,[]
32134,Unknown,2006-04-28,1986.0,Quinretta,F,32135,White,None,,,None,[]
32135,Unknown,2016-12-12,1991.0,Grzegorz,M,32136,Wilczek,None,,,None,[]
32136,Unknown,2008-04-07,1977.0,Michael,M,32137,Wilson,None,,,None,[]
32137,Unknown,2002-01-07,1978.0,Steven,M,32138,Witnik,None,,,None,[]
32138,Unknown,2013-11-16,1995.0,Nicholas,M,32139,Wright,None,,,None,[]
32139,Unknown,2016-08-29,1988.0,Edyta,F,32140,Zuk,None,,,None,[]

Currently, `active` and `rank` are still missing. We will update when this data is available